
-- --------------------------------------------------------

--
-- Structure for view `mt_view_merchant`
--
DROP TABLE IF EXISTS `mt_view_merchant`;

CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `mt_view_merchant`  AS  select `a`.`merchant_id` AS `merchant_id`,`a`.`restaurant_slug` AS `restaurant_slug`,`a`.`restaurant_name` AS `restaurant_name`,`a`.`restaurant_phone` AS `restaurant_phone`,`a`.`contact_name` AS `contact_name`,`a`.`contact_phone` AS `contact_phone`,`a`.`contact_email` AS `contact_email`,`a`.`country_code` AS `country_code`,`a`.`street` AS `street`,`a`.`city` AS `city`,`a`.`state` AS `state`,`a`.`post_code` AS `post_code`,`a`.`cuisine` AS `cuisine`,`a`.`service` AS `service`,`a`.`free_delivery` AS `free_delivery`,`a`.`delivery_estimation` AS `delivery_estimation`,`a`.`username` AS `username`,`a`.`password` AS `password`,`a`.`activation_key` AS `activation_key`,`a`.`activation_token` AS `activation_token`,`a`.`status` AS `status`,`a`.`date_created` AS `date_created`,`a`.`date_modified` AS `date_modified`,`a`.`date_activated` AS `date_activated`,`a`.`last_login` AS `last_login`,`a`.`ip_address` AS `ip_address`,`a`.`package_id` AS `package_id`,`a`.`package_price` AS `package_price`,`a`.`membership_expired` AS `membership_expired`,`a`.`payment_steps` AS `payment_steps`,`a`.`is_featured` AS `is_featured`,`a`.`is_ready` AS `is_ready`,`a`.`is_sponsored` AS `is_sponsored`,`a`.`sponsored_expiration` AS `sponsored_expiration`,`a`.`lost_password_code` AS `lost_password_code`,`a`.`user_lang` AS `user_lang`,`a`.`membership_purchase_date` AS `membership_purchase_date`,`a`.`sort_featured` AS `sort_featured`,`a`.`is_commission` AS `is_commission`,`a`.`percent_commision` AS `percent_commision`,`a`.`abn` AS `abn`,`a`.`session_token` AS `session_token`,`a`.`commision_type` AS `commision_type`,`b`.`option_value` AS `latitude`,`c`.`option_value` AS `lontitude`,`d`.`option_value` AS `delivery_charges`,`e`.`option_value` AS `minimum_order`,`f`.`ratings` AS `ratings` from (((((`mt_merchant` `a` left join `mt_option` `b` on(((`a`.`merchant_id` = `b`.`merchant_id`) and (`b`.`option_name` = 'merchant_latitude')))) left join `mt_option` `c` on(((`a`.`merchant_id` = `c`.`merchant_id`) and (`c`.`option_name` = 'merchant_longtitude')))) left join `mt_option` `d` on(((`a`.`merchant_id` = `d`.`merchant_id`) and (`d`.`option_name` = 'merchant_delivery_charges')))) left join `mt_option` `e` on(((`a`.`merchant_id` = `e`.`merchant_id`) and (`e`.`option_name` = 'merchant_minimum_order')))) left join `mt_view_ratings` `f` on((`a`.`merchant_id` = `f`.`merchant_id`))) ;
